(module
  (import "wasi_snapshot_preview1" "fd_write"
(func $fd_write (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $A (mut i64) (i64.const 0))
  (global $B (mut i64) (i64.const 0))
  (global $C (mut i64) (i64.const 0))
  (func $print_i64 (param $val i64)
    (local $neg i32)
    (local $uval i64)
    (local $pos i32)
    (local $digit i64)
    (if (i64.eqz (local.get $val))
      (then
        (i32.store8 (i32.const 31) (i32.const 48))
        (i32.store (i32.const 32) (i32.const 31))
        (i32.store (i32.const 36) (i32.const 1))
        (drop (call $fd_write (i32.const 1) (i32.const 32) (i32.const 1) (i32.const 40)))
        return
      )
    )
    (local.set $neg (i64.lt_s (local.get $val) (i64.const 0)))
    (if (local.get $neg)
      (then (local.set $uval (i64.sub (i64.const 0) (local.get $val))))
      (else (local.set $uval (local.get $val)))
    )
    (local.set $pos (i32.const 31))
    (block $brk
      (loop $top
        (br_if $brk (i64.eqz (local.get $uval)))
        (local.set $digit (i64.rem_u (local.get $uval) (i64.const 10)))
        (i32.store8
          (local.get $pos)
          (i32.add (i32.const 48) (i32.wrap_i64 (local.get $digit)))
        )
        (local.set $pos (i32.sub (local.get $pos) (i32.const 1)))
        (local.set $uval (i64.div_u (local.get $uval) (i64.const 10)))
        (br $top)
      )
    )
    (if (local.get $neg)
      (then
        (i32.store8 (local.get $pos) (i32.const 45))
        (local.set $pos (i32.sub (local.get $pos) (i32.const 1)))
      )
    )
    (i32.store (i32.const 32) (i32.add (local.get $pos) (i32.const 1)))
    (i32.store (i32.const 36) (i32.sub (i32.const 31) (local.get $pos)))
    (drop (call $fd_write (i32.const 1) (i32.const 32) (i32.const 1) (i32.const 40)))
  )
  (func $_start (export "_start")
    (global.set $C (i64.add (global.get $C) (i64.const 1)))
    (global.set $C (i64.add (global.get $C) (i64.const 1)))
    (block $exit_0
      (loop $top_0
        (br_if $exit_0 (i64.ge_s (global.get $A) (global.get $C)))
        (global.set $A (i64.add (global.get $A) (i64.const 1)))
        (br $top_0)
      )
    )
    (call $print_i64 (global.get $A))
  )
)
